version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - WEATHER_API_KE=${fec734c51bd96203d583749fb62d52e6}
    networks:
      - weather-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "5000:5000"
    networks:
      - weather-network

networks:
  weather-network:
    driver: bridge
