version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - API_KEY=fec734c51bd96203d583749fb62d52e6
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
